server.port=8080

# Cấu hình Cơ sở dữ liệu PostgreSQL (Khớp với báo cáo đề tài)
spring.datasource.url=jdbc:postgresql://localhost:5432/milktea_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Tự động chuyển sang H2 Memory Database nếu chưa bật PostgreSQL Server (Tránh báo lỗi khi demo)
spring.datasource.continue-on-error=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cho phép CORS cho Flutter Web
management.endpoints.web.exposure.include=*
