name: frontend_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Ăn vặt Hàn Quốc
    - assets/images/anvathanquoc/Bingsoo/
    - assets/images/anvathanquoc/chaca/
    - assets/images/anvathanquoc/Dalgona/
    - assets/images/anvathanquoc/Gimbap/
    - assets/images/anvathanquoc/Hotteok/
    - assets/images/anvathanquoc/Japchae/
    - assets/images/anvathanquoc/kimbap/
    - assets/images/anvathanquoc/mandu/
    - assets/images/anvathanquoc/tokbokki/
    - assets/images/anvathanquoc/tteokbanhgaonuong/
    # Ăn vặt mặn
    - assets/images/anvatman/banhgaochien/
    - assets/images/anvatman/bapxaobo/
    - assets/images/anvatman/boviennuong/
    - assets/images/anvatman/cavienchien/
    - assets/images/anvatman/dauhuchienmam/
    - assets/images/anvatman/khoaitaychien/
    - assets/images/anvatman/nemchuaran/
    - assets/images/anvatman/phomaique/
    - assets/images/anvatman/trungcutchien/
    - assets/images/anvatman/xucxich/
    # Bánh & đồ ngọt
    - assets/images/banh&dongot/banhbonglan/
    - assets/images/banh&dongot/banhdonutphuduong/
    - assets/images/banh&dongot/banhmochinhandaudo/
    - assets/images/banh&dongot/banhsukem/
    - assets/images/banh&dongot/crepematcha/
    - assets/images/banh&dongot/cupcake/
    - assets/images/banh&dongot/puddingcaramel/
    - assets/images/banh&dongot/tartsuadua/
    - assets/images/banh&dongot/tiramisu/
    - assets/images/banh&dongot/waffle/
    # Đồ ăn cay
    - assets/images/doancay/banhtrangcuon/
    - assets/images/doancay/banhtrangtron/
    - assets/images/doancay/bokhosate/
    - assets/images/doancay/changacay/
    - assets/images/doancay/gacaychiengion/
    - assets/images/doancay/lauminicay/
    - assets/images/doancay/micay/
    - assets/images/doancay/micayHancap5/
    - assets/images/doancay/mucrimsate/
    - assets/images/doancay/tokbokkicayngot/
    - assets/images/doancay/trungvitlonsotcay/
    # Món no nhẹ
    - assets/images/monnonhe/banhgio/
    - assets/images/monnonhe/banhmiopla/
    - assets/images/monnonhe/banhuotcuonthit/
    - assets/images/monnonhe/chaoyenmach/
    - assets/images/monnonhe/comchienduongchau/
    - assets/images/monnonhe/comcuon/
    - assets/images/monnonhe/comcuon_vn/
    - assets/images/monnonhe/miIndomie/
    - assets/images/monnonhe/mitron/
    - assets/images/monnonhe/nuixao/
    - assets/images/monnonhe/phocuonrau/
    - assets/images/monnonhe/sandwichcangu/
    - assets/images/monnonhe/xoibap/
    # Nước uống
    - assets/images/nuocuong/cacao/cacaodua/
    - assets/images/nuocuong/cacao/cacaonongda/
    - assets/images/nuocuong/cacao/caccaosua/
    - assets/images/nuocuong/nuocep/cam/
    - assets/images/nuocuong/nuocep/dua/
    - assets/images/nuocuong/nuocep/duahau/
    - assets/images/nuocuong/nuocep/le/
    - assets/images/nuocuong/nuocep/nho/
    - assets/images/nuocuong/nuocep/tao/
    - assets/images/nuocuong/nuocep/xoai/
    - assets/images/nuocuong/tradao/
    - assets/images/nuocuong/trasua/duongden/
    - assets/images/nuocuong/trasua/matcha/
    - assets/images/nuocuong/trasua/olong/
    - assets/images/nuocuong/trasua/thai/
    - assets/images/nuocuong/trasua/truyenthong/
    - assets/images/nuocuong/tratac/
    # Snack & kẹo
    - assets/images/snack&keo/banhquybo/
    - assets/images/snack&keo/caramelmem/
    - assets/images/snack&keo/chocolate/
    - assets/images/snack&keo/keodeo/
    - assets/images/snack&keo/keololipop/
    - assets/images/snack&keo/oishi/
    - assets/images/snack&keo/poca/
    - assets/images/snack&keo/rongbien/
    - assets/images/snack&keo/snackkhoailang/
    - assets/images/snack&keo/snackmucthai/
    # Trái cây & chua
    - assets/images/traicay&dochua/chomchomtuoi/
    - assets/images/traicay&dochua/chuoisay/
    - assets/images/traicay&dochua/coclac/
    - assets/images/traicay&dochua/dualacmuoi/
    - assets/images/traicay&dochua/khechuamuoiot/
    - assets/images/traicay&dochua/man/
    - assets/images/traicay&dochua/me/
    - assets/images/traicay&dochua/oilac/
    - assets/images/traicay&dochua/saungamduong/
    - assets/images/traicay&dochua/xoailac/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
